// src/shared/constants/routerxErrorCodes.js
// Error codes for RouterX structured error objects

export const ROUTERX_ERROR_CODES = {
  // API related errors
  API_ERROR_400: 'API_ERROR_400',
  API_ERROR_401: 'API_ERROR_401',
  API_ERROR_402: 'API_ERROR_402',
  API_ERROR_403: 'API_ERROR_403',
  API_ERROR_404: 'API_ERROR_404',
  API_ERROR_429: 'API_ERROR_429',
  API_ERROR_500: 'API_ERROR_500',
  API_ERROR_502: 'API_ERROR_502',
  API_ERROR_503: 'API_ERROR_503',
  API_ERROR_504: 'API_ERROR_504',
  NETWORK_ERROR: 'NETWORK_ERROR',
  REQUEST_ERROR: 'REQUEST_ERROR',
  
  // Configuration related errors
  CONFIG_VALIDATION_ERROR: 'CONFIG_VALIDATION_ERROR',
  CONFIG_LOAD_ERROR: 'CONFIG_LOAD_ERROR',
  MISSING_CONFIG_VALUE: 'MISSING_CONFIG_VALUE',
  
  // File related errors
  FILE_READ_ERROR: 'FILE_READ_ERROR',
  FILE_WRITE_ERROR: 'FILE_WRITE_ERROR',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  DIRECTORY_CREATE_ERROR: 'DIRECTORY_CREATE_ERROR',
  
  // Validation related errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INPUT_VALIDATION_ERROR: 'INPUT_VALIDATION_ERROR',
  PARAMETER_ERROR: 'PARAMETER_ERROR',
  
  // General application errors
  APPLICATION_ERROR: 'APPLICATION_ERROR',
  UNHANDLED_ERROR: 'UNHANDLED_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR'
};